version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: increase
    groups:
      worker-tooling:
        patterns:
          - "@biomejs/biome"
          - "@cloudflare/workers-types"
          - "prettier"
          - "typescript"
          - "vitest"
          - "wrangler"
        update-types:
          - "major"
          - "minor"
          - "patch"
      runtime:
        patterns:
          - "hono"
          - "mercadopago"
          - "zod"
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
